### PR TITLE
Add About and Contact components with routing and styling

### PR DESCRIPTION
**Pull request by Abhinav8639**
### Related Issue
- Closes: #6 

---

### Description

In this pull request, I have added the **About** and **Contact** components to the project. I also replaced the `<a>` anchor tags in the `Navbar` component with `Link` components from `react-router-dom` to prevent page reloads when navigating between pages. This ensures a smooth single-page application experience.

1. Run `npm install` to install the necessary dependencies.
2. Run `npm run dev` to start the development server.

---

### How Has This Been Tested?

Tested the navigation by clicking the links in the `Navbar` (Home, About, Contact) and verified that the page does not reload.
- Confirmed that the About and Contact pages are rendered correctly without any issues.

---

### Screenshots (if applicable)

Screenshot (5636)](https://github.com/user-attachments/assets/a154c661-748d-40c9-b62e-f3cefb73bd5f)
25)

---

### Type of Change

- [ ] Bug fix
- [v ] New feature
- [ ] Code style update
- [ ] Breaking change
- [ ] Documentation update

### CODE REVIEW

**Comment by mehul-m-prajapati** [comment]
@Abhinav8639 : you have pasted same code here. Please see review changes of your previous pr and do the changes here

**Comment by Abhinav8639** [comment]
Thank you so much for your patience 
i have removed the html files
I had one quick question: in the navigation bar, should I replace the <a> tags with Link from React Router, or should I keep the anchor tags as they are? Please let me know if this change is required.
Thanks again for your time and help!

**Comment by mehul-m-prajapati** [comment]
@Abhinav8639 : you need to use link from react router only

**Comment by mehul-m-prajapati** [comment]
Why have you renamed dashboard to home?

Please revert that change

**Pull request merged**
